/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Friends;

import FIRSTPAGE.*;
import static FIRSTPAGE.HOME.nmm;
import static Friends.DisplayFriends.nm_fr;
import Log.Login;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author garli
 */
public class FriendRecipes  extends javax.swing.JFrame {
    
    private int count=0;
    static Connection connection = null;
    PreparedStatement pst = null;
    PreparedStatement ps = null;
    PreparedStatement ps2 = null;
    PreparedStatement prs= null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    ResultSet res = null;
    public static String nm_recfr;
    public static String addid=null;
    public static String nfr=null;
    public int cc1=0;
    public  int cc2=0;
    public  int cc3=0;
    public  int cc4=0;
    public  int cc5=0;
    public  int cc6=0;
    public  int l=0;
    public  int cr=0;
    public  int o=0;
    public  int fr=0;
    public  int le=0;
    public  int ce=0;
    
    
   
    
   
    /**
     * Creates new form Page1
     * @throws java.sql.SQLException
     */
    public FriendRecipes() throws SQLException  {
        initComponents();
        flname.setText(nmm); 
        DisplayTable();
        Seticon();
    }
    
    public final void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoLTD.png")));
    }
    
    private void DisplayTable() throws SQLException{
    try{   
           
           
           
           connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/licenta", "root","000000"); 
           String query="SELECT * FROM licenta.login  WHERE fullname ='"+nm_fr+"'";
           ps =connection.prepareStatement(query);
            String sql;
           rs = ps.executeQuery();
            if(rs.next()){
            addid=rs.getString("id");
            nfr=rs.getString("fullname");}
            rfname.setText(nfr);
            if(lac.isSelected() || car.isSelected() || ou.isSelected()|| fruc.isSelected() || leg.isSelected() || cer.isSelected()){
             sql="SELECT name as NAME FROM licenta.recipes WHERE type='PUBLIC' AND id ='"+addid+"' AND  (`dairy_products`='"+l+"' or IF('"+l+"'=1,`dairy_products`=1,`dairy_products`=`dairy_products`))  AND  (`meat`='"+cr+"' OR IF('"+cr+"'=1,`meat`=1,`meat`=`meat`)) AND  (`egg`='"+o+"' OR IF('"+o+"'=1,`egg`=1,`egg`=`egg`)) AND  (`fruit`='"+fr+"' OR IF('"+fr+"'=1,`fruit`=1,`fruit`=`fruit`)) AND  (`vegetables`='"+le+"' OR IF('"+le+"'=1,`vegetables`=1,`vegetables`=`vegetables`)) AND  (`cereals`='"+ce+"' OR IF('"+ce+"'=1,`cereals`=1,`cereals`=`cereals`))";       
             ps2 =connection.prepareStatement(sql);
                                              rs2 = ps2.executeQuery();  
                                              if(res.next()){
                                                l=Integer.parseInt(res.getString("dairy_products"));
                                                cr=Integer.parseInt(res.getString("meat"));
                                                o=Integer.parseInt(res.getString("egg"));
                                                fr=Integer.parseInt(res.getString("fruit"));
                                                le=Integer.parseInt(res.getString("vegetables"));
                                                ce=Integer.parseInt(res.getString("cereals"));}
            }else{sql="SELECT name as NAME FROM licenta.recipes WHERE id ='"+addid+"' AND type='PUBLIC'";}
            pst =connection.prepareStatement(sql);
            res = pst.executeQuery();
            t3.setModel(DbUtils.resultSetToTableModel(res));
            
           
       }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,"Eror .");
				}  
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setResizable(false);
        jPanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        flname = new javax.swing.JLabel();
        blo = new javax.swing.JButton();
        bf = new javax.swing.JButton();
        bmr = new javax.swing.JButton();
        opmen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTable();
        bop = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cer = new javax.swing.JCheckBox();
        lac = new javax.swing.JCheckBox();
        car = new javax.swing.JCheckBox();
        ou = new javax.swing.JCheckBox();
        fruc = new javax.swing.JCheckBox();
        leg = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        rfname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TastyDiary");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 236, 193));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.hide();
        menu.setBackground(new java.awt.Color(228, 236, 193));
        menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 230, 208));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\garli\\OneDrive\\Desktop\\Licenta\\iconite\\user (1).png")); // NOI18N
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        flname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        flname.setText("name");
        menu.add(flname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, 20));

        blo.setBackground(new java.awt.Color(255, 230, 208));
        blo.setText("IEȘIRE CONT");
        blo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bloMouseExited(evt);
            }
        });
        blo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloActionPerformed(evt);
            }
        });
        menu.add(blo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        bf.setBackground(new java.awt.Color(255, 230, 208));
        bf.setText("PRIETENI");
        bf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bfMouseExited(evt);
            }
        });
        bf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfActionPerformed(evt);
            }
        });
        menu.add(bf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, -1));

        bmr.setBackground(new java.awt.Color(255, 230, 208));
        bmr.setText("REȚETELE MELE");
        bmr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bmrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bmrMouseExited(evt);
            }
        });
        bmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmrActionPerformed(evt);
            }
        });
        menu.add(bmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, -1));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 390));

        opmen.setBackground(new java.awt.Color(255, 230, 208));
        opmen.setIcon(new javax.swing.ImageIcon("C:\\Users\\garli\\OneDrive\\Desktop\\Licenta\\iconite\\menu (1).png")); // NOI18N
        opmen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opmenMouseClicked(evt);
            }
        });
        opmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmenActionPerformed(evt);
            }
        });
        jPanel1.add(opmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        t3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(t3);
        t3.getAccessibleContext().setAccessibleName("r");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 540, 290));

        bop.setBackground(new java.awt.Color(255, 230, 208));
        bop.setText("DESCHIDE");
        bop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bopMouseExited(evt);
            }
        });
        bop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bopActionPerformed(evt);
            }
        });
        jPanel1.add(bop, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        jLabel3.setText("LAPTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 20));

        jLabel4.setText("CARNE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 20));

        jLabel5.setText("OUA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 20));

        jLabel6.setText("FRUCTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 20));

        jLabel7.setText("LEGUME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, 20));

        jLabel8.setText("CEREALE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 20));

        cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerActionPerformed(evt);
            }
        });
        jPanel1.add(cer, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        lac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lacActionPerformed(evt);
            }
        });
        jPanel1.add(lac, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carActionPerformed(evt);
            }
        });
        jPanel1.add(car, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        ou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouActionPerformed(evt);
            }
        });
        jPanel1.add(ou, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        fruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frucActionPerformed(evt);
            }
        });
        jPanel1.add(fruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        leg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legActionPerformed(evt);
            }
        });
        jPanel1.add(leg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(228, 236, 193));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 810, 40));
        jPanel1.add(rfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void legActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legActionPerformed
        cc5++;
        if(cc5%2==0){
            leg.setSelected(false);
            le=0;

            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            leg.setSelected(true);
            le=1;
            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_legActionPerformed

    private void frucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frucActionPerformed
        cc4++;
        if(cc4%2==0){
            fruc.setSelected(false);
            fr=0;

            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            fruc.setSelected(true);
            fr=1;
            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_frucActionPerformed

    private void ouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouActionPerformed
        cc3++;
        if(cc3%2==0){
            ou.setSelected(false);
            o=0;

            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            ou.setSelected(true);
            o=1;
            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ouActionPerformed

    private void carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carActionPerformed
        cc2++;
        if(cc2%2==0){
            car.setSelected(false);
            cr=0;

            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            car.setSelected(true);
            cr=1;
            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_carActionPerformed

    private void lacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lacActionPerformed

        cc1++;
        if(cc1%2==0){
            lac.setSelected(false);
            l=0;
            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            lac.setSelected(true);
            l=1;
            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lacActionPerformed

    private void cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerActionPerformed
        cc6++;
        if(cc6%2==0){
            cer.setSelected(false);
             ce =0 ;
            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            cer.setSelected(true);
            ce=1;
            try {
                DisplayTable();
            } catch (SQLException ex) {
                Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cerActionPerformed

    private void bopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bopActionPerformed
        try {
            int row=t3.getSelectedRow();
            nm_recfr=t3.getModel().getValueAt(row,0).toString();
            dispose();
            DisplayFrRec frec=new DisplayFrRec();
            frec.setVisible(true);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bopActionPerformed

    private void opmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opmenActionPerformed

    private void opmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opmenMouseClicked

        count++;
        if ( count % 2 == 0 ){
            menu.hide();
        }
        else{
            menu.show();
        }

    }//GEN-LAST:event_opmenMouseClicked

    private void bmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmrActionPerformed
        try {
            dispose();
            MyRecipes recc=new MyRecipes();
            recc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bmrActionPerformed

    private void bfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfActionPerformed
        try {
            dispose();
            DisplayFriends p=new DisplayFriends();
            p.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FriendRecipes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bfActionPerformed

    private void bloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloActionPerformed
        dispose();
        Login log= new Login();
        log.setVisible(true);
    }//GEN-LAST:event_bloActionPerformed

    private void bmrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmrMouseEntered
        bmr.setBackground(Color.GRAY);
    }//GEN-LAST:event_bmrMouseEntered

    private void bmrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmrMouseExited
        bmr.setBackground( new Color(255,230,208));
    }//GEN-LAST:event_bmrMouseExited

    private void bfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bfMouseEntered
       bf.setBackground(Color.GRAY);
    }//GEN-LAST:event_bfMouseEntered

    private void bfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bfMouseExited
        bf.setBackground( new Color(255,230,208));
    }//GEN-LAST:event_bfMouseExited

    private void bloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloMouseEntered
        blo.setBackground(Color.GRAY);
    }//GEN-LAST:event_bloMouseEntered

    private void bloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloMouseExited
        blo.setBackground( new Color(255,230,208));
    }//GEN-LAST:event_bloMouseExited

    private void bopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bopMouseEntered
        bop.setBackground(Color.GRAY);
    }//GEN-LAST:event_bopMouseEntered

    private void bopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bopMouseExited
        bop.setBackground( new Color(255,230,208));
    }//GEN-LAST:event_bopMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HOME().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bf;
    private javax.swing.JButton blo;
    private javax.swing.JButton bmr;
    private javax.swing.JButton bop;
    private javax.swing.JCheckBox car;
    private javax.swing.JCheckBox cer;
    private javax.swing.JLabel flname;
    private javax.swing.JCheckBox fruc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lac;
    private javax.swing.JCheckBox leg;
    private javax.swing.JPanel menu;
    private javax.swing.JButton opmen;
    private javax.swing.JCheckBox ou;
    private javax.swing.JLabel rfname;
    private javax.swing.JTable t3;
    // End of variables declaration//GEN-END:variables


}
