package Log;


import FIRSTPAGE.HOME;
import Register.Register;
import password.ForgotPassword;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author garli
 */
public class Login extends javax.swing.JFrame {
    static Connection connection = null;
	PreparedStatement pst = null;
	ResultSet rs = null;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        breg = new javax.swing.JButton();
        blog1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fpas = new javax.swing.JLabel();
        luser = new javax.swing.JTextField();
        lpass = new javax.swing.JPasswordField();
        remember = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(205, 92, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        breg.setBackground(new java.awt.Color(255, 230, 208));
        breg.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        breg.setText("REGISTER");
        breg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        breg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        breg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bregMouseExited(evt);
            }
        });
        breg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregActionPerformed(evt);
            }
        });
        jPanel1.add(breg, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 170, 50));

        blog1.setBackground(new java.awt.Color(255, 230, 208));
        blog1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        blog1.setText("LOGIN");
        blog1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        blog1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blog1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blog1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blog1MouseExited(evt);
            }
        });
        blog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blog1ActionPerformed(evt);
            }
        });
        jPanel1.add(blog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 170, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 40, 50));

        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 40, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Remember me");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 130, 30));

        fpas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fpas.setText("Forgot password?");
        fpas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fpas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpasMouseClicked(evt);
            }
        });
        jPanel1.add(fpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, 30));

        luser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(luser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 300, 30));
        luser.getAccessibleContext().setAccessibleName("username");

        lpass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(lpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 300, 30));
        lpass.getAccessibleContext().setAccessibleName("password");

        remember.setBackground(new java.awt.Color(255, 230, 208));
        remember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberActionPerformed(evt);
            }
        });
        jPanel1.add(remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\garli\\OneDrive\\Desktop\\Licenta\\log bunaur.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 1110, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1120, 660));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregActionPerformed
        dispose();
        Register r= new Register();
        r.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bregActionPerformed

    private void fpasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpasMouseClicked
        dispose();
        ForgotPassword f= new ForgotPassword();
        f.setVisible(true);
        
    }//GEN-LAST:event_fpasMouseClicked

    private void rememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberActionPerformed
        
    }//GEN-LAST:event_rememberActionPerformed

    private void blog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blog1ActionPerformed
        
        try {
					String sql = "SELECT * FROM licenta.login WHERE username =? and password =? ";
					connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/licenta", "root","000000");
					pst = connection.prepareStatement(sql);
					pst.setString(1, luser.getText());
					pst.setString(2, lpass.getText());
					rs = pst.executeQuery();
					if (rs.next()) {			
							String fullname = rs.getString("fullname");
                                                        dispose();
                                                        HOME.nmm=fullname;
							HOME p=new HOME();
                                                        p.setVisible(true);
						
						 

					} else {
                                            JOptionPane.showMessageDialog(null, "Invalid Username or Password");
						
                                               
					}
				} catch (HeadlessException | SQLException p) {
					JOptionPane.showMessageDialog(null, p);
				}
        
        
        
    }//GEN-LAST:event_blog1ActionPerformed

    private void blog1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blog1MouseEntered
        blog1.setBackground(Color.GRAY);
    }//GEN-LAST:event_blog1MouseEntered

    private void blog1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blog1MouseExited
       blog1.setBackground( new Color(255,230,208));
    }//GEN-LAST:event_blog1MouseExited

    private void bregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bregMouseEntered
       breg.setBackground(Color.GRAY);
    }//GEN-LAST:event_bregMouseEntered

    private void bregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bregMouseExited
        breg.setBackground( new Color(255,230,208));
    }//GEN-LAST:event_bregMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blog1;
    private javax.swing.JButton breg;
    private javax.swing.JLabel fpas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField lpass;
    private javax.swing.JTextField luser;
    private javax.swing.JCheckBox remember;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new Login().setVisible(true);
        }
    }
}
